# Generated by Django 6.1.1 on 2026-09-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of the title (auto-generate if unsure)",
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Short summary shown on the projects page"
                    ),
                ),
                (
                    "tech_stack",
                    models.CharField(
                        help_text="Comma-separated, e.g. Python, Django, PostgreSQL",
                        max_length=300,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("github_url", models.URLField(blank=True, null=True)),
                ("live_url", models.URLField(blank=True, null=True)),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Show this project prominently"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
